services:
  mariadb:
    image: mariadb:10.11
    container_name: my_mariadb_container
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: secret123
      MARIADB_DATABASE: daamdb
      MARIADB_USER: root
      MARIADB_PASSWORD: secret123
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

  backend-service:

    build:
      context: ./java_backend/server
      dockerfile: Dockerfile
    container_name: backend_service
    restart: unless-stopped
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/daamdb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=secret123
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
    networks:
      - app-network

  ui-client:
    image: node:latest
    container_name: ui_client
    restart: unless-stopped
    environment:
      - NEXT_PUBLIC_DAAM_API_URL=http://backend-service:8080
    volumes:
      - ./ui-client:/app
    working_dir: /app
    command: sh -c "npm install -g pnpm && pnpm install && pnpm run dev"
    ports:
      - "3000:3000"
    depends_on:
      - backend-service
    networks:
      - app-network

volumes:
  mariadb_data:
    driver: local

networks:
  app-network:
    driver: bridge
